### ISSUE TITLE
run_delete fails

### ISSUE THREAD

**Issue by kaaage** [tira-io/tira#144]
**Current behavior**

ERROR 2021-11-14 17:35:17,175 log: Internal Server Error: /grpc/kolyada21z/run_delete/clickbait17-test-170720/2021-11-12-17-51-10
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tira/tira-application/src/./tira/checks.py", line 38, in func_wrapper
    return func(request, *args, **kwargs)
  File "/tira/tira-application/src/./tira/checks.py", line 97, in func_wrapper
    if not model.run_exists(kwargs["vm_id"], kwargs["dataset_id"], kwargs["software_id"]):
KeyError: 'software_id'

**UI error**
_vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:10113 GET https://www.tira.io/grpc/nikolay21a/run_delete/clickbait17-test-170720/2021-11-15-17-43-12 500
send @ _vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:10113
ajax @ _vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:9696
deleteRun @ software.js:368
(anonymous) @ software.js:332
dispatch @ _vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:5443
g.handle @ _vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:5247
software.js:377 Uncaught ReferenceError: vmid is not defined
    at Object.error (software.js:377)
    at u (_vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:3510)
    at Object.fireWith [as rejectWith] (_vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:3640)
    at O (_vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:9802)
    at XMLHttpRequest.<anonymous> (_vendor-4ae2a802777e3846717e32bbdeff48e04293223e1952666c62f02ba3b3af179c.js:10061)

**Expected behavior**

**Comment by kaaage** [comment]
Fixed by 106e62d71198294ad0abe60a8954fcd389d8fd7d

**Comment by kaaage** [comment]
Probably some discord routing issue?

https://www.tira.io/grpc/nikolay21a/run_delete/clickbait17-test-170720/2021-11-15-18-09-03

`Oops! That page doesn’t exist or is private.`

**Comment by BastianGrahm** [comment]
When do you get the `Oops!` page? This link points to an action in the application and afaik shouldn't return HTML as a response.

**Comment by kaaage** [comment]
Just while trying to access this endpoint, but I guess it's similar to #148 (Disraptor gets `Failed to load resource: the server responded with a status of 500 ()` from the application).

**Comment by kaaage** [comment]
Superseded by #150 150
