### ISSUE TITLE
Running the Evaluator does not work

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#160]
**Current behavior**
When clicking on the evaluator button, I get an Internal Server error in the frontend.

I did not have an exhaustive look in the logs so far, but this is the error in the frontend-log:

```
ERROR 2021-12-09 15:07:04,835 actions: /grpc/test-user-04/run_eval/touche-2022-task2/2021-12-03-11-51-28: connection failed with <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception deserializing request!"
	debug_error_string = "{"created":"@1639058824.835195748","description":"Error received from peer ipv4:141.54.132.42:50051","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception deserializing request!","grpc_status":13}"
>
Traceback (most recent call last):
  File "./tira/actions.py", line 39, in func_wrapper
    response = func(request, *args, **kwargs)
  File "./tira/actions.py", line 537, in run_eval
    response = grpc_client.run_eval(vm_id=evaluator["vm_id"],
  File "./tira/grpc_client.py", line 38, in func_wrapper
    response = func(self, *args, transaction=grpc_transaction, **kwargs)
  File "./tira/grpc_client.py", line 148, in run_eval
    response = self.stub.run_eval(tira_host_pb2.RunDetails(transaction=transaction,
  File "/usr/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Exception deserializing request!"
	debug_error_string = "{"created":"@1639058824.835195748","description":"Error received from peer ipv4:141.54.132.42:50051","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception deserializing request!","grpc_status":13}"
```

**Comment by kaaage** [comment]
ERROR 2022-02-15 12:16:18,088 vm_api: /grpc/princess-knight/run_eval/touche-2022-task2/2022-02-15-12-03-38: Server Error: Cannot query "Dataset object (touche-2022-task2)": Must be "Evaluator" instance.
Traceback (most recent call last):
  File "/tira/tira-application/src/./tira/endpoints/vm_api.py", line 32, in func_wrapper
    response = func(request, *args, **kwargs)
  File "/tira/tira-application/src/./tira/endpoints/vm_api.py", line 297, in run_eval
    evaluator = model.get_evaluator(dataset_id)
  File "/tira/tira-application/src/./tira/tira_model.py", line 126, in get_evaluator
    return model.get_evaluator(dataset_id, task_id)
  File "/tira/tira-application/src/./tira/data/HybridDatabase.py", line 539, in get_evaluator
    master_vm = modeldb.VirtualMachineHasEvaluator.objects.filter(evaluator=evaluator)[0].vm
  File "/usr/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1302, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1134, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/usr/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1115, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "Dataset object (touche-2022-task2)": Must be "Evaluator" instance.
ERROR 2022-02-15 12:16:18,526 log: Internal Server Error: /grpc/princess-knight/run_eval/touche-2022-task2/2022-02-15-12-03-38
