### ISSUE TITLE
Error building application venv

### ISSUE THREAD

**Issue by BastianGrahm** [tira-io/tira#182]
Rebuilding the applications venv via `make venv` reports
```
...
Collecting mysqlclient (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/webis/tira/tira-application/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7sqqxmrw/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7sqqxmrw/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-7sqqxmrw/mysqlclient/
    Complete output (15 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7sqqxmrw/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-7sqqxmrw/mysqlclient/setup_posix.py", line 70, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-7sqqxmrw/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    mysql_config --version
    mariadb_config --version
    mysql_config --libs
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by MattiWe** [comment]
Can you try installing mysql before running the requirements file?

**Comment by BastianGrahm** [comment]
Didn't work but this does:
`sudo apt-get install libmysqlclient-dev`

Source:
https://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface?page=1&tab=votes#tab-top
