### ISSUE TITLE
Add dataset does not allow to add an evaluator with the tiragit workflow

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#242]
When I click on add dataset, I can only add the evaluators that use a virtual machine:

![Screenshot_20220813_074557](https://user-images.githubusercontent.com/10050886/184470549-75f1452f-f8b5-40d9-9de8-fb8d9eaf0d70.png)

Only for "Edit Dataset" I get the new formula:
![Screenshot_20220813_074557](https://user-images.githubusercontent.com/10050886/184470618-2fafec3a-4638-4300-98ec-79285d588aec.png)

**Expected behavior**
I should be able to get the new formula also for the "Add dataset" form.

**Comment by mam10eks** [comment]
Adding a dataset (to later edit it to ad the git CI) does not work, there seems to be an exception here:

https://github.com/tira-io/tira/blob/development/application/src/tira/endpoints/admin_api.py#L169

The stacktrace is:

```
ERROR 2022-08-13 07:55:34,054 log: Internal Server Error: /tira-admin/add-dataset
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tira/application/src/./tira/checks.py", line 34, in func_wrapper
    return func(request, *args, **kwargs)
  File "/tira/application/src/./tira/endpoints/admin_api.py", line 169, in admin_add_dataset
    upload_name = data["upload_name"]
KeyError: 'upload_name'
```

**Comment by mam10eks** [comment]
I am able to add a new dataset with curl (by manually adding the missing fields).

However, when I now click on evaluate, I get another error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tira/application/src/./tira/checks.py", line 85, in func_wrapper
    return func(request, *args, **kwargs)
  File "/tira/application/src/./tira/checks.py", line 180, in func_wrapper
    return func(request, *args, **kwargs)
  File "/tira/application/src/./tira/endpoints/vm_api.py", line 333, in run_eval
    if evaluator.is_git_runner:
AttributeError: 'dict' object has no attribute 'is_git_runner'
```

**Comment by mam10eks** [comment]
This was fixed.
